server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.181.140:3306/vhr
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0

  cache:
    cache-names: menu_cache
    redis:
      time-to-live: 1800s


mybatis:
  mapper-locations: classpath:/mybatis-config.xml


